1.NumPy: - Execute different NumPy array operations.

In [1]:
import numpy as np
a=np.array(42)           #0-D Array
b=np.array([1,2,3])      #1-D Arrays
c=np.array([[1,2,3],[4,5,6]])     #2-D Arrays

In [2]:
d= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3-D Arrays
e=np.array((1, 2, 3, 4, 5))     #1-D Array from tuple
f= np.array([1, 2, 3, 4], ndmin=5)  #High Dimentional Array

In [3]:
#Print the array.
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print("Each item contains",a.itemsize,"bytes")

42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[1 2 3 4 5]
[[[[[1 2 3 4]]]]]
Each item contains 8 bytes


In [4]:
#The type of array.
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
#Numbers of Dimensions.
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


In [6]:
#Array Indexing.
print("The value is=",c[1][2])
print("The value is=",b[0])
print("The value is=",b[-2])    #Negative Indexing
print("The value is=",c[-1][-2])

The value is= 6
The value is= 1
The value is= 2
The value is= 5


In [7]:
#Array slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])   #1 D Array
print(arr[:4])
print(arr[2:])
print(arr[1:6:2])
print(arr[-1:-5:-2])

[1 2 3 4]
[3 4 5 6 7]
[2 4 6]
[7 5]


In [8]:
#Linspace
a=np.linspace(5,15,10) #prints 10 values which are evenly spaced over the given interval 5-15  
print(a) 

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [9]:
#NumPy Array Axis
a = np.array([[1,2,30],[10,15,4]])  
print("The array:",a)  
print("The maximum elements of columns:",a.max(axis = 0))   
print("The minimum element of rows",a.min(axis = 1))  
print("The sum of all rows",a.sum(axis = 1))  

The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum element of rows [1 4]
The sum of all rows [33 29]


In [10]:
#zeroes() 
array = np.zeros([2,3])  
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#ones() 
array = np.ones([2,3])  
print(array)  

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#eye()
array = np.eye(4)  
print(array)
array = np.ones([2,3])  
print(array)  

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#empty()
x = np.empty([3, 2])  
print(x)   

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
#reshape
#reshape 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(2, 3, 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
#Random
from numpy import random
x=random.randint(100, size=(5))
print(x)

[98 92  0 67 37]
