3. NumPy: - Universal functions in NumPy (Trigonometric).

In [ ]:
import numpy as np
angles = np.array([0, 30, 45, 60, 90, 180])

# conversion of degree into radians
# using deg2rad function
radians = np.deg2rad(angles)
radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [ ]:
# conversion of degree into radians
# using rad2deg function
degree = np.rad2deg(angles)
degree

array([    0.        ,  1718.87338539,  2578.31007809,  3437.74677078,
        5156.62015618, 10313.24031235])

In [ ]:
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(sine_value)

Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]


In [ ]:
print('Inverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))

Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]


In [ ]:
print('Sine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(np.sinh(radians))

Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]


In [ ]:
print('Inverse Sine hyperbolic:')
print(np.sin(sineh_value)) 

Inverse Sine hyperbolic:
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]


In [ ]:
print('Sine of angles in the array:')
cos_value = np.cos(radians)
print(cos_value)

Sine of angles in the array:
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]


In [ ]:
print('Sine of angles in the array:')
arcsin_value = np.arcsin(radians)
print(arcsin_value)

Sine of angles in the array:
[0.         0.55106958 0.90333911        nan        nan        nan]


<ipython-input-8-3ee938bcf085>:2: RuntimeWarning: invalid value encountered in arcsin
  arcsin_value = np.arcsin(radians)


In [ ]:
print('Hyperbolic inverse sine:')
sine_value = np.arcsinh(radians)
print(sine_value)

Hyperbolic inverse sine:
[0.         0.50221899 0.72122549 0.91435666 1.23340312 1.86229574]


In [ ]:
print('Hyperbolic inverse cos:')
sine_value = np.arcsinh(radians)
print(sine_value)

Hyperbolic inverse cos:
[0.         0.50221899 0.72122549 0.91435666 1.23340312 1.86229574]


In [ ]:
print('Hyperbolic inverse tan:')
sine_value = np.arcsinh(radians)
print(sine_value)

Hyperbolic inverse tan:
[0.         0.50221899 0.72122549 0.91435666 1.23340312 1.86229574]


In [ ]:
# hypot function demonstration
base = 4
height = 3
print('hypotenuse of right triangle is:')
print(np.hypot(base, height))

hypotenuse of right triangle is:
5.0


In [ ]:
#bitwise_and  
a = 10  
b = 12  
print("binary representation of a:",bin(a))   
print("Bitwise-and of a and b: ",np.bitwise_and(a,b))

binary representation of a: 0b1010
Bitwise-and of a and b:  8


In [ ]:
#bitwies_or 
a = 50  
b = 90    
print("Bitwise-or of a and b: ",np.bitwise_or(a,b)) 

Bitwise-or of a and b:  122


In [ ]:
#bitwise_xor
print("Bitwise-or representation:",np.bitwise_xor(28, 5))
print("Binary-or representation:",np.bitwise_xor([28, 3], 7))

Bitwise-or representation: 25
Binary-or representation: [27  4]


In [ ]:
#invert
arr = np.array([20],dtype = np.uint8)  
print("Binary representation:",np.binary_repr(20,8))  
print(np.invert(arr)) 

Binary representation: 00010100
[235]


In [ ]:
#left_shift
print("left shift of 20 by 3 bits",np.left_shift(20, 3))  
print("Binary representation of 20 in 8 bits",np.binary_repr(20, 8))   

left shift of 20 by 3 bits 160
Binary representation of 20 in 8 bits 00010100


In [ ]:
#right_shift
print("left shift of 20 by 3 bits",np.right_shift(20, 3))  
print("Binary representation of 20 in 8 bits",np.binary_repr(20, 8))  

left shift of 20 by 3 bits 2
Binary representation of 20 in 8 bits 00010100
