5. Indexing & Slicing: - Indexing & slicing operations on 2 D NumPy array.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])     #2-D Arrays

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("Each item contains",a.itemsize,"bytes")

Each item contains 8 bytes


In [ ]:
#The type of array.
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#Numbers of Dimensions.
print(a.ndim)

2


In [ ]:
#Array Indexing.
print("The value is=",a[1][2])
print("The value is=",a[0])
print("The value is=",a[-2])    #Negative Indexing
print("The value is=",a[-1][-2])

The value is= 6
The value is= [1 2 3]
The value is= [1 2 3]
The value is= 5


In [ ]:
#Array Slicing
a=a+1;
print(a)
print(a.sum())
print(a[1,1:2])
print(a[0:1,1])
print(a[:,:-1])
print(a[:,:1])

[[2 3 4]
 [5 6 7]]
27
[6]
[3]
[[2 3]
 [5 6]]
[[2]
 [5]]


In [ ]:
arr1 = np.array([[1, 2, 3, 4, 5],             #2 D Array
                 [6, 7, 8, 9, 10]])
print(arr1[0,1:4])
print(arr1[1,1:4])

print(arr1[0:2,1:4])

print(arr1[0:2,3:6])

[2 3 4]
[7 8 9]
[[2 3 4]
 [7 8 9]]
[[ 4  5]
 [ 9 10]]
